title: Research Review Notes
description: Summaries of academic research papers
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
include: ['_reviews']
github:
  is_project_page: True
